/* ============================================================================
 * panels/robot_scene/panel.js — the 3D scene panel.
 *
 * Renders whatever scenes/<scene>/scene.json describes — scene bundles are
 * generated by `cramera-onboard` from real coraplex demo runs. Also owns the
 * playback / live controls and the layers overlay.
 *
 * Scene selection: ?scene=<name> URL parameter, else scenes/index.json default.
 *
 * Bus events:
 *   emits    scene:part-clicked {id}   click on a robot part / object
 *   emits    scene:step {step}         playback entered a plan step ('__done__' at end)
 *   emits    live:changed {on, url}    live bridge attached / detached
 *   listens  entity:highlight {ids}    glow the matching 3D objects
 *
 * window.RobotView stays exported for the console and split-resize.
 * ==========================================================================*/
Panels.define('robot-scene', function (root, bus) {
  root.innerHTML =
    '<div class="panel-head">' +
    '  <h2>Semantic Digital Twin Scene</h2>' +
    '  <select id="scene-select" class="scene-select" style="display:none"></select>' +
    '</div>' +
    '<div class="stage">' +
    '  <div id="stage-bg" class="stage-bg"></div>' +
    '  <div id="viewer"></div>' +
    '  <div id="viewer-status" class="viewer-status">Loading scene…</div>' +
    '  <div id="layers-panel" class="layers-panel">' +
    '    <div class="lp-title">Layers</div>' +
    '    <label class="lp-row"><input type="checkbox" id="lyr-objects" checked><span>Bench objects</span></label>' +
    '    <label class="lp-row"><input type="checkbox" id="lyr-labels"><span>Object labels</span></label>' +
    '    <label class="lp-row"><input type="checkbox" id="lyr-floor" checked><span>Floor shadow</span></label>' +
    '    <div class="lp-legend" id="lp-legend"></div>' +
    '  </div>' +
    '  <div id="live-indicator" class="live-indicator">● LIVE</div>' +
    '  <div id="step-caption" class="step-caption hidden"></div>' +
    '  <div class="stage-hint">drag orbit · scroll zoom · right-drag pan · drag objects &amp; the blue place target</div>' +
    '</div>' +
    '<div class="workflow">' +
    '  <div class="workflow-head"><span class="wf-btns">' +
    '    <button id="live-btn" class="play-btn live" style="display:none" title="Attach to the running demo (cramera-live bridge) — renders the live world instead of the recording">◉ Live</button>' +
    '    <button id="play-btn" class="play-btn cram" title="Play the recorded coraplex + giskardpy motion trajectory">▶ Play robot motion</button>' +
    '  </span></div>' +
    '</div>';
  function $(id) { return root.querySelector('#' + id); }

  console.log('%c[cramera] robot-scene panel', 'color:#39d5c8;font-weight:bold');
  const container = $('viewer');
  const statusEl = $('viewer-status');
  const SCENES = 'scenes/';

  //: how often the viewer asks whether a live bridge is reachable, in ms
  const LIVE_PROBE_INTERVAL_MS = 3000;
  //: how long after mount imported materials keep being re-tamed, in seconds
  const MATERIAL_SETTLE_SECONDS = 25;

  const scene3 = new THREE.Scene();
  scene3.background = null;

  const camera = new THREE.PerspectiveCamera(45, 1, 0.01, 200);
  camera.position.set(3, 2.4, 4);

  const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  renderer.shadowMap.enabled = true;
  renderer.shadowMap.type = THREE.PCFSoftShadowMap;
  renderer.outputEncoding = THREE.sRGBEncoding;
  renderer.toneMapping = THREE.ACESFilmicToneMapping;
  renderer.toneMappingExposure = 0.95;
  container.appendChild(renderer.domElement);

  // soft vertical-gradient studio backdrop
  (function () {
    const cv = document.createElement('canvas');
    cv.width = 2; cv.height = 256;
    const ctx = cv.getContext('2d');
    const g = ctx.createLinearGradient(0, 0, 0, 256);
    g.addColorStop(0, '#232833'); g.addColorStop(0.55, '#151922'); g.addColorStop(1, '#0c0e13');
    ctx.fillStyle = g; ctx.fillRect(0, 0, 2, 256);
    scene3.background = new THREE.CanvasTexture(cv);
  })();

  // image-based lighting (imported .dae lights are stripped on load)
  if (THREE.RoomEnvironment && THREE.PMREMGenerator) {
    try {
      const pmrem = new THREE.PMREMGenerator(renderer);
      scene3.environment = pmrem.fromScene(new THREE.RoomEnvironment(), 0.04).texture;
    } catch (e) { /* optional */ }
  }

  scene3.add(new THREE.HemisphereLight(0xf4efe6, 0x2a2d33, 0.32));
  scene3.add(new THREE.AmbientLight(0xfff4e6, 0.05));
  const key = new THREE.DirectionalLight(0xfff2df, 1.05);
  key.position.set(4, 7, 3);
  key.castShadow = true;
  key.shadow.mapSize.set(4096, 4096);
  key.shadow.camera.near = 0.5; key.shadow.camera.far = 30;
  key.shadow.camera.left = -6; key.shadow.camera.right = 6;
  key.shadow.camera.top = 6; key.shadow.camera.bottom = -6;
  key.shadow.bias = -0.0003;
  key.shadow.normalBias = 0.02;
  key.shadow.radius = 3;
  scene3.add(key);
  const back = new THREE.DirectionalLight(0xdfe6f2, 0.3);
  back.position.set(-4, 4, -3);
  scene3.add(back);

  // %% procedural textures (floor planks)
  function floorTexture() {
    const cv = document.createElement('canvas'); cv.width = 512; cv.height = 512;
    const ctx = cv.getContext('2d');
    ctx.fillStyle = '#b9a184'; ctx.fillRect(0, 0, 512, 512);
    const plank = 512 / 6;
    for (let r = 0; r < 6; r++) {
      const shade = 168 + ((r * 37) % 40) - 20;
      ctx.fillStyle = 'rgb(' + (shade + 20) + ',' + (shade - 4) + ',' + (shade - 30) + ')';
      ctx.fillRect(0, r * plank, 512, plank - 2);
      ctx.strokeStyle = 'rgba(60,40,25,0.35)'; ctx.lineWidth = 2;
      ctx.strokeRect(0, r * plank, 512, plank - 2);
      for (let i = 0; i < 40; i++) {
        ctx.strokeStyle = 'rgba(90,60,40,0.06)';
        const y = r * plank + Math.random() * plank;
        ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(512, y + (Math.random() - 0.5) * 4); ctx.stroke();
      }
    }
    const t = new THREE.CanvasTexture(cv);
    t.wrapS = t.wrapT = THREE.RepeatWrapping; t.anisotropy = 8;
    return t;
  }
  function woodTexture(base, streak) {
    const cv = document.createElement('canvas'); cv.width = 256; cv.height = 256;
    const ctx = cv.getContext('2d');
    ctx.fillStyle = base; ctx.fillRect(0, 0, 256, 256);
    for (let i = 0; i < 220; i++) {
      const y = Math.floor((i / 220) * 256) + (i % 3);
      ctx.strokeStyle = 'rgba(' + streak + ',' + (0.03 + (i % 5) * 0.015) + ')';
      ctx.lineWidth = 1 + (i % 3);
      ctx.beginPath(); ctx.moveTo(0, y);
      for (let x = 0; x <= 256; x += 16) ctx.lineTo(x, y + Math.sin((x + i) * 0.05) * 1.5);
      ctx.stroke();
    }
    const t = new THREE.CanvasTexture(cv);
    t.wrapS = t.wrapT = THREE.RepeatWrapping; t.anisotropy = 8;
    return t;
  }
  const WOOD_COUNTER = woodTexture('#9c6b3f', '70,45,25');
  const WOOD_TABLE = woodTexture('#b98a52', '90,60,35');

  const floorTex = floorTexture();
  floorTex.repeat.set(12, 12);
  const ground = new THREE.Mesh(
    new THREE.PlaneGeometry(60, 60),
    new THREE.MeshStandardMaterial({ map: floorTex, roughness: 0.85, metalness: 0.0 })
  );
  ground.rotation.x = -Math.PI / 2;
  ground.receiveShadow = true;
  scene3.add(ground);

  const controls = new THREE.OrbitControls(camera, renderer.domElement);
  controls.enableDamping = true;
  controls.dampingFactor = 0.08;
  controls.minDistance = 1;
  controls.maxDistance = 25;
  controls.maxPolarAngle = Math.PI * 0.5;

  // z-up (URDF/map) -> three y-up
  const worldRoot = new THREE.Group();
  worldRoot.rotation.x = -Math.PI / 2;
  scene3.add(worldRoot);

  let needsRender = true;
  controls.addEventListener('change', function () { needsRender = true; });

  // %% scene
  let SCENE = null;              // scene.json payload
  let sceneBase = null;          // static/scenes/<name>/
  let traj = null;
  const models = [];             // {name, prefix, robot, obj}
  let robotModel = null;
  const objectMeshes = {};       // mesh key ('milk.stl') -> THREE.Group
  const objectLabels = {};       // mesh key -> label sprite
  const liveSpawned = {};        // mesh key -> true for objects added by live mode
  const objectPending = {};      // mesh key -> true while its geometry is loading
  let labelsOn = false;
  const objectIdByKey = {}, objectKeyById = {};
  const _objLoader = new THREE.STLLoader();   // no manager: for live/on-demand loads

  // add one draggable object to the scene (bundle load or live spawn). spec:
  // {id, key, color, meshUrl?, format?  |  box:[x,y,z]}. Any mesh format the
  // vendored loaders support (stl/obj/dae) works; unknown → placeholder box.
  function addObject(spec) {
    // present, or its mesh is still in flight — the live reconcile runs at 15 Hz
    // and would otherwise re-request the same STL dozens of times before it lands
    if (objectMeshes[spec.key] || objectPending[spec.key]) return;
    objectPending[spec.key] = true;
    objectIdByKey[spec.key] = spec.id;
    objectKeyById[spec.id] = spec.key;
    const mat = new THREE.MeshStandardMaterial({
      color: new THREE.Color(spec.color || '#cccccc'),
      roughness: 0.5, metalness: 0.05, envMapIntensity: 0.7,
    });
    function place(content) {                  // content: Mesh or Object3D
      content.traverse(function (c) {
        if (c.isMesh) {
          c.castShadow = true; c.receiveShadow = true;
          if (spec.tame && c.material && c.material.emissive) c.material.emissive.setRGB(0, 0, 0);
        }
      });
      const g = new THREE.Group();
      g.add(content);
      const box = new THREE.Box3().setFromObject(content);
      const top = isFinite(box.max.z) ? box.max.z : 0.15;
      const label = makeLabel(spec.id.replace(/_/g, ' '), spec.color);
      label.position.z = top + 0.09;
      label.visible = labelsOn;
      g.add(label);
      objectLabels[spec.key] = label;
      objectMeshes[spec.key] = g;
      delete objectPending[spec.key];
      worldRoot.add(g);
      needsRender = true;
    }
    function box(scale) {
      const s = scale || [0.06, 0.06, 0.1];
      place(new THREE.Mesh(new THREE.BoxGeometry(s[0], s[1], s[2]).translate(0, 0, s[2] / 2), mat));
    }
    if (spec.box) { box(spec.box); return; }
    const fmt = (spec.format || (spec.meshUrl || '').split('?')[0].split('.').pop() || '').toLowerCase();
    if (fmt === 'obj' && THREE.OBJLoader) {
      new THREE.OBJLoader().load(spec.meshUrl, function (o) {
        o.traverse(function (c) { if (c.isMesh) c.material = mat; });
        place(o);
      }, undefined, function () { box(); });
    } else if (fmt === 'dae' && THREE.ColladaLoader) {
      spec.tame = true;                         // dae carries its own (possibly glowing) materials
      new THREE.ColladaLoader().load(spec.meshUrl, function (c) { place(c.scene); },
        undefined, function () { box(); });
    } else {
      _objLoader.load(spec.meshUrl, function (geom) { place(new THREE.Mesh(geom, mat)); },
        undefined, function () { box(); });
    }
  }
  function removeObject(key) {
    const g = objectMeshes[key];
    if (!g) return;
    worldRoot.remove(g);
    g.traverse(function (c) {
      if (c.geometry) c.geometry.dispose();
      if (c.material) { c.material.map && c.material.map.dispose(); c.material.dispose(); }
    });
    delete objectMeshes[key]; delete objectLabels[key];
    delete objectIdByKey[key]; delete liveSpawned[key]; delete objectPending[key];
  }

  // canvas-sprite name tag, colour-dotted to match the object
  function makeLabel(text, color) {
    const pad = 16, fs = 34, dot = 22;
    const cv = document.createElement('canvas');
    let ctx = cv.getContext('2d');
    ctx.font = '600 ' + fs + 'px Inter, sans-serif';
    cv.width = ctx.measureText(text).width + pad * 2 + dot + 10;
    cv.height = fs + pad * 2;
    ctx = cv.getContext('2d');
    ctx.font = '600 ' + fs + 'px Inter, sans-serif';
    ctx.fillStyle = 'rgba(10,17,32,0.82)';
    const r = 12, w = cv.width, h = cv.height;
    ctx.beginPath();
    ctx.moveTo(r, 0); ctx.arcTo(w, 0, w, h, r); ctx.arcTo(w, h, 0, h, r);
    ctx.arcTo(0, h, 0, 0, r); ctx.arcTo(0, 0, w, 0, r); ctx.closePath();
    ctx.fill();
    ctx.strokeStyle = 'rgba(57,213,200,0.5)'; ctx.lineWidth = 2; ctx.stroke();
    ctx.fillStyle = color || '#39d5c8';
    ctx.beginPath(); ctx.arc(pad + dot / 2, h / 2, dot / 2, 0, Math.PI * 2); ctx.fill();
    ctx.fillStyle = '#e8eefb'; ctx.textBaseline = 'middle';
    ctx.fillText(text, pad + dot + 10, h / 2);
    const tex = new THREE.CanvasTexture(cv);
    tex.anisotropy = 4;
    const spr = new THREE.Sprite(new THREE.SpriteMaterial({ map: tex, transparent: true, depthTest: false }));
    const s = 0.0016;
    spr.scale.set(cv.width * s, cv.height * s, 1);
    return spr;
  }
  let linkToPart = {};           // link name -> part name (from robot.parts)
  const readyCbs = [];
  let finalized = false;

  const manager = new THREE.LoadingManager();
  function makeUrdfLoader() {
    const loader = new URDFLoader(manager);
    loader.packages = {};
    loader.parseCollision = false;
    const def = loader.defaultMeshLoader.bind(loader);
    loader.loadMeshCb = function (path, mgr, done) {
      if (/\.obj$/i.test(path)) {
        new THREE.OBJLoader(mgr).load(path, function (o) { done(o); },
          undefined, function () { done(new THREE.Object3D()); });
      } else {
        def(path, mgr, done);
      }
    };
    return loader;
  }

  function sceneNameFromUrl() {
    const m = /[?&]scene=([\w-]+)/.exec(window.location.search);
    return m ? m[1] : null;
  }

  fetch(SCENES + 'index.json')
    .then(function (r) { return r.ok ? r.json() : { default: null, scenes: [] }; })
    .catch(function () { return { default: null, scenes: [] }; })
    .then(function (index) {
      const name = sceneNameFromUrl() || index.default;
      // header dropdown: switch between all onboarded scenes
      const sel = $('scene-select');
      if (sel && index.scenes && index.scenes.length > 1) {
        sel.innerHTML = index.scenes.map(function (s) {
          return '<option value="' + s + '"' + (s === name ? ' selected' : '') + '>' + s + '</option>';
        }).join('');
        sel.style.display = '';
        sel.addEventListener('change', function () {
          window.location.search = '?scene=' + encodeURIComponent(sel.value);
        });
      }
      if (!name) {
        if (statusEl) statusEl.textContent = 'No scene found — run cramera-onboard first.';
        return;
      }
      sceneBase = SCENES + name + '/';
      return fetch(sceneBase + 'scene.json').then(function (r) { return r.json(); }).then(loadScene);
    })
    .catch(function (e) {
      if (statusEl) statusEl.textContent = 'Scene failed to load: ' + e;
    });

  function loadScene(sc) {
    SCENE = sc;
    if (statusEl) statusEl.textContent = 'Loading ' + sc.name + '…';
    // robot part lookup (link -> part name)
    linkToPart = {};
    const parts = (sc.robot && sc.robot.parts) || {};
    for (const part in parts) parts[part].forEach(function (l) { linkToPart[l] = part; });

    sc.models.forEach(function (m) {
      makeUrdfLoader().load(sceneBase + m.urdf, function (obj) {
        const entry = { name: m.name, prefix: m.prefix || '', robot: !!m.robot, obj: obj };
        models.push(entry);
        if (m.robot) robotModel = entry;
        worldRoot.add(obj);
        needsRender = true;
      });
    });

    (sc.objects || []).forEach(function (o) {
      addObject({ id: o.id, key: o.key, meshUrl: sceneBase + o.mesh, color: o.color });
    });

    buildMarker(sc.placeTarget);
    manager.onLoad = function () {
      upgradeMaterials();
      if (!finalized) finalize();
      needsRender = true;
    };
    [1500, 4000, 9000, 13000].forEach(function (ms) {
      setTimeout(function () {
        if (models.length) { upgradeMaterials(); dropGroundToScene(); needsRender = true; }
      }, ms);
    });
    setTimeout(function () { if (models.length) finalize(); }, 15000);
  }

  function finalize() {
    if (finalized) return;
    finalized = true;
    upgradeMaterials();
    dropGroundToScene();
    fetch(sceneBase + (SCENE.trajectory || 'trajectory.json'))
      .then(function (r) { return r.ok ? r.json() : null; })
      .then(function (d) {
        traj = d;
        setupTransports();
        if (traj) applyFrame(0);
        frameCamera();
        if (statusEl) statusEl.classList.add('hidden');
        readyCbs.forEach(function (cb) { cb(); });
        needsRender = true;
      }).catch(function () {
        frameCamera();
        if (statusEl) statusEl.classList.add('hidden');
        readyCbs.forEach(function (cb) { cb(); });
      });
  }

  // %% materials (identical treatment to the hand-built version)
  function tameMat(mat) {
    if (!mat) return;
    if (mat.emissive) mat.emissive.setRGB(0, 0, 0);
    mat.emissiveIntensity = 0;
    if (mat.color) {
      const lum = (mat.color.r + mat.color.g + mat.color.b) / 3;
      if (lum > 0.92) mat.color.setRGB(0.82, 0.82, 0.83);
    }
    if (mat.isMeshPhongMaterial) { mat.shininess = 25; if (mat.specular) mat.specular.setRGB(0.05, 0.05, 0.05); }
    if ('roughness' in mat) mat.roughness = Math.min(Math.max(mat.roughness || 0.7, 0.4), 0.92);
    if ('metalness' in mat) mat.metalness = Math.min(mat.metalness || 0, 0.2);
    if ('envMapIntensity' in mat) mat.envMapIntensity = 0.45;
    mat.needsUpdate = true;
  }
  function linkNameOf(c) {
    let o = c;
    while (o) { if (o.isURDFLink && o.name) return String(o.name); o = o.parent; }
    return '';
  }
  // furniture palette, keyed on common link-name vocabulary — applies to any
  // environment model; unmatched links keep their tamed authored look
  function themeEnvironment(mat, link) {
    tameMat(mat);
    const n = link.toLowerCase();
    if (/cooktop|hotplate|ceran|stove/.test(n)) {
      mat.color.setHex(0x0a0b0d); mat.map = null; mat.roughness = 0.18; mat.metalness = 0.15;
    } else if (/island_countertop|countertop|worktop/.test(n)) {
      mat.color.setHex(0xffffff); mat.map = WOOD_COUNTER; mat.roughness = 0.55; mat.metalness = 0.02;
    } else if (/coffee_table|table_area|bedside_table|table_top|dining/.test(n)) {
      mat.color.setHex(0xffffff); mat.map = WOOD_TABLE; mat.roughness = 0.5; mat.metalness = 0.02;
    } else if (/handle|tap_body|tap_handle|sink|faucet/.test(n)) {
      mat.color.setHex(0xc6ccd4); mat.map = null; mat.roughness = 0.28; mat.metalness = 0.85;
    } else if (/cabinet|drawer|door|wardrobe|dishwasher|oven|coffe_machine|island_back|island_waterfall|side_[ab]|fridge/.test(n)) {
      mat.color.setHex(0x1b1d21); mat.map = null; mat.roughness = 0.42; mat.metalness = 0.12;
    } else if (/wall/.test(n)) {
      mat.color.setHex(0xd9d4cb); mat.map = null; mat.roughness = 0.95; mat.metalness = 0.0;
    }
    mat.needsUpdate = true;
  }
  const OWN_LIGHTS = new Set();
  scene3.traverse(function (c) { if (c.isLight) OWN_LIGHTS.add(c); });
  function stripImportedLights(root) {
    const kill = [];
    root.traverse(function (c) { if (c.isLight && !OWN_LIGHTS.has(c)) kill.push(c); });
    kill.forEach(function (l) { if (l.parent) l.parent.remove(l); });
  }
  function tameModel(entry) {
    stripImportedLights(entry.obj);
    entry.obj.traverse(function (c) {
      if (!c.isMesh || c.userData._tamed) return;
      c.castShadow = true; c.receiveShadow = true;
      const link = entry.robot ? '' : linkNameOf(c);
      const mats = Array.isArray(c.material) ? c.material : [c.material];
      mats.forEach(function (m) { entry.robot ? tameMat(m) : themeEnvironment(m, link); });
      c.userData._tamed = true;
    });
  }
  function upgradeMaterials() { models.forEach(tameModel); }

  function dropGroundToScene() {
    const envs = models.filter(function (m) { return !m.robot; });
    if (!envs.length) return;
    const box = new THREE.Box3();
    envs.forEach(function (m) { box.expandByObject(m.obj); });
    if (!isFinite(box.min.y) || !isFinite(box.min.x)) return;
    const w = (box.max.x - box.min.x) + 0.4;
    const d = (box.max.z - box.min.z) + 0.4;
    ground.geometry.dispose();
    ground.geometry = new THREE.PlaneGeometry(w, d);
    ground.position.set((box.min.x + box.max.x) / 2, box.min.y + 0.002, (box.min.z + box.max.z) / 2);
    floorTex.repeat.set(w / 0.6, d / 0.6);
    floorTex.needsUpdate = true;
    needsRender = true;
  }

  // %% playback
  let playing = false, playhead = 0, stepCb = function () {};
  let lastStep = null;
  const _p0 = new THREE.Vector3(), _p1 = new THREE.Vector3();
  const _q0 = new THREE.Quaternion(), _q1 = new THREE.Quaternion();

  function setPose(obj, a, b, t) {
    _p0.set(a[0], a[1], a[2]); _p1.set(b[0], b[1], b[2]);
    obj.position.copy(_p0).lerp(_p1, t);
    _q0.set(a[3], a[4], a[5], a[6]); _q1.set(b[3], b[4], b[5], b[6]);
    obj.quaternion.copy(_q0).slerp(_q1, t);
  }
  function modelByPrefix(prefix) {
    for (let i = 0; i < models.length; i++) if (models[i].prefix === prefix) return models[i];
    return null;
  }

  function applyFrame(f) {
    if (!traj) return;
    const F = traj.frames, i0 = Math.floor(f), i1 = Math.min(i0 + 1, F.length - 1), t = f - i0;
    const f0 = F[i0], f1 = F[i1];
    for (const k in f0) {
      const cut = k.indexOf('/');
      const m = modelByPrefix(cut < 0 ? '' : k.slice(0, cut));
      if (!m) continue;
      const j = m.obj.joints[cut < 0 ? k : k.slice(cut + 1)];
      if (j) j.setJointValue(f0[k] + ((f1[k] !== undefined ? f1[k] : f0[k]) - f0[k]) * t);
    }
    if (robotModel && traj.base && traj.base[i0]) {
      setPose(robotModel.obj, traj.base[i0], traj.base[i1] || traj.base[i0], t);
      const bo = baseOffsetAt(f);
      robotModel.obj.position.x += bo.x; robotModel.obj.position.y += bo.y;
    }
    if (traj.objects) {
      const o0 = traj.objects[i0], o1 = traj.objects[i1];
      for (const name in objectMeshes) {
        if (o0[name] && o1[name]) {
          setPose(objectMeshes[name], o0[name], o1[name], t);
          const oo = objOffsetAt(name, f);
          objectMeshes[name].position.x += oo.x;
          objectMeshes[name].position.y += oo.y;
          // while the object is still resting (before its pick), hold the
          // dragged surface height so it doesn't float / clip
          const pd = pickDeltas[name];
          if (pd && pd.zAbs != null && restingBeforePick(name, f)) {
            objectMeshes[name].position.z = pd.zAbs;
          }
        }
      }
    }
    if (SCENE && SCENE.segments) {
      const seg = SCENE.segments.find(function (s) { return i0 >= s.start && i0 < s.end; });
      if (seg && seg.step !== lastStep) { lastStep = seg.step; stepCb(seg.step); }
    }
  }

  function playTrajectory() {
    if (!traj) return false;
    playing = true; playhead = 0; lastStep = null;
    return true;
  }
  function stopTrajectory() { playing = false; }

  // %% adjustable pick spawns + place target
  // The scene records for each manipulation segment which object moves and its
  // attach/detach frames — no detection heuristics needed here.
  const pickDeltas = {};         // mesh key -> {x,y}
  const placeDelta = { x: 0, y: 0 };
  const ZERO = { x: 0, y: 0 };
  let PLACE0 = null;
  let transports = [];
  const spawn0 = {};

  function smooth(u) { u = Math.min(1, Math.max(0, u)); return u * u * (3 - 2 * u); }

  function setupTransports() {
    transports = [];
    if (!SCENE || !traj) return;
    (SCENE.objects || []).forEach(function (o) {
      pickDeltas[o.key] = { x: 0, y: 0, zAbs: null };
      spawn0[o.key] = o.spawn.slice();
    });
    (SCENE.segments || []).forEach(function (s) {
      if (!s.picks || s.attach === undefined || s.detach === undefined) return;
      const key = objectKeyById[s.picks];
      if (key) transports.push({ obj: key, start: s.start, end: s.end, attach: s.attach, detach: s.detach });
    });
  }

  function restingBeforePick(name, f) {
    for (let k = 0; k < transports.length; k++) {
      if (transports[k].obj === name) return f < transports[k].attach;
    }
    return true;   // never picked → always resting
  }

  function objOffsetAt(name, f) {
    for (let k = 0; k < transports.length; k++) {
      const tr = transports[k];
      if (tr.obj !== name) continue;
      const pd = pickDeltas[name] || ZERO;
      if (f < tr.attach) return pd;
      if (f < tr.detach) {
        const u = smooth((f - tr.attach) / (tr.detach - tr.attach));
        return { x: pd.x + (placeDelta.x - pd.x) * u, y: pd.y + (placeDelta.y - pd.y) * u };
      }
      return placeDelta;
    }
    return pickDeltas[name] || ZERO;
  }
  function baseOffsetAt(f) {
    for (let k = 0; k < transports.length; k++) {
      const tr = transports[k];
      if (f < tr.start || f >= tr.end) continue;
      const pd = pickDeltas[tr.obj] || ZERO;
      if (f < tr.attach) {
        const w = smooth((f - tr.start) / Math.max(1, tr.attach - tr.start));
        return { x: pd.x * w, y: pd.y * w };
      }
      if (f < tr.detach) {
        const u = smooth((f - tr.attach) / (tr.detach - tr.attach));
        return { x: pd.x + (placeDelta.x - pd.x) * u, y: pd.y + (placeDelta.y - pd.y) * u };
      }
      const w2 = 1 - smooth((f - tr.detach) / Math.max(1, tr.end - tr.detach));
      return { x: placeDelta.x * w2, y: placeDelta.y * w2 };
    }
    return ZERO;
  }

  // %% camera
  let follow = true;
  const _target = new THREE.Vector3(), _base = new THREE.Vector3();
  function frameCamera() {
    if (!robotModel) return;
    const box = new THREE.Box3().setFromObject(robotModel.obj);
    const c = box.getCenter(new THREE.Vector3());
    controls.target.copy(c);
    camera.position.set(c.x + 3.2, c.y + 1.6, c.z + 3.4);
    controls.update();
    needsRender = true;
  }
  function robotCenter(out) {
    if (!robotModel) return false;
    robotModel.obj.getWorldPosition(_base);
    out.copy(_base); out.y += 0.6;
    return true;
  }

  // %% place-target marker (blue corner brackets)
  const marker = new THREE.Group();
  let MARKER_LIMIT = null;
  function buildMarker(pt) {
    if (!pt) { marker.visible = false; return; }
    const blue = 0x35a7ff;
    const barMat = new THREE.MeshBasicMaterial({ color: blue });
    const hx = 0.30, hy = 0.22, L = 0.14, W = 0.022, H = 0.012;
    [[-1, -1], [1, -1], [-1, 1], [1, 1]].forEach(function (c) {
      const armX = new THREE.Mesh(new THREE.BoxGeometry(L, W, H), barMat);
      armX.position.set(c[0] * (hx - L / 2), c[1] * hy, 0);
      const armY = new THREE.Mesh(new THREE.BoxGeometry(W, L, H), barMat);
      armY.position.set(c[0] * hx, c[1] * (hy - L / 2), 0);
      marker.add(armX, armY);
    });
    const fill = new THREE.Mesh(
      new THREE.PlaneGeometry(hx * 2, hy * 2),
      new THREE.MeshBasicMaterial({ color: blue, transparent: true, opacity: 0.08, depthWrite: false })
    );
    marker.add(fill);
    PLACE0 = { x: pt.position[0], y: pt.position[1] };
    MARKER_LIMIT = pt.bounds;
    marker.position.set(PLACE0.x, PLACE0.y, pt.z);
    worldRoot.add(marker);
  }

  // %% drag + click-to-inspect
  const dragRay = new THREE.Raycaster(), dragNdc = new THREE.Vector2();
  const dragStartNdc = new THREE.Vector2(), dragStartWorld = new THREE.Vector3();
  const camR = new THREE.Vector3(), camF = new THREE.Vector3(), camU = new THREE.Vector3();
  const _w = new THREE.Vector3();
  let dragTarget = null, dragging = false;
  let clickX = 0, clickY = 0, clickArmed = false;
  let partClickCb = null;

  function objLimit() {
    return (SCENE && SCENE.dragBounds) || { minX: -50, maxX: 50, minY: -50, maxY: 50 };
  }
  function pointerNdc(e) {
    const r = renderer.domElement.getBoundingClientRect();
    dragNdc.set(((e.clientX - r.left) / r.width) * 2 - 1, -((e.clientY - r.top) / r.height) * 2 + 1);
  }
  function draggableMeshes() {
    const list = [];
    for (const n in objectMeshes) {
      objectMeshes[n].traverse(function (c) { if (c.isMesh) { c.userData.simObj = n; list.push(c); } });
    }
    if (marker.visible !== false) {
      marker.traverse(function (c) { if (c.isMesh) { c.userData.simMarker = true; list.push(c); } });
    }
    return list;
  }
  function pickDraggable(e) {
    pointerNdc(e);
    dragRay.setFromCamera(dragNdc, camera);
    const hits = dragRay.intersectObjects(draggableMeshes(), false);
    if (!hits.length) return null;
    const o = hits[0].object;
    if (o.userData.simMarker) return { group: marker, marker: true };
    return { group: objectMeshes[o.userData.simObj], name: o.userData.simObj };
  }

  // %% surface snapping: rest a dragged object on whatever is beneath it
  // cast a ray straight down through the object and drop it onto the highest
  // surface (table, counter, another object, else the floor) — never floating.
  const DOWN = new THREE.Vector3(0, -1, 0);
  const _ray = new THREE.Raycaster();
  let _envMeshes = null;
  function envMeshes() {
    if (_envMeshes) return _envMeshes;
    _envMeshes = [];
    models.forEach(function (m) {
      if (m.robot) return;
      m.obj.traverse(function (c) { if (c.isMesh) _envMeshes.push(c); });
    });
    if (ground) _envMeshes.push(ground);
    return _envMeshes;
  }
  function meshBox(group) {                 // world AABB over the object's meshes only (skip label sprite)
    const box = new THREE.Box3(); box.makeEmpty();
    group.traverse(function (c) { if (c.isMesh) box.expandByObject(c); });
    return box;
  }
  function surfaceTargets(excludeKey) {     // env + floor + the OTHER objects
    const targets = envMeshes().slice();
    for (const k in objectMeshes) {
      if (k !== excludeKey && objectMeshes[k].visible) {
        objectMeshes[k].traverse(function (o) { if (o.isMesh) targets.push(o); });
      }
    }
    return targets;
  }
  // cursor -> world point on the horizontal drag plane (infinite, so the object
  // follows the cursor anywhere — the surface height is fixed afterwards by
  // snapToSurface). The plane is set through the grab point on pointerdown.
  const _dragPlane = new THREE.Plane();
  const _hitPt = new THREE.Vector3();
  function surfacePointAt(e) {
    pointerNdc(e);
    _ray.setFromCamera(dragNdc, camera);
    return _ray.ray.intersectPlane(_dragPlane, _hitPt) ? _hitPt.clone() : null;
  }
  function snapToSurface(group, excludeKey) {
    const box = meshBox(group);
    if (!isFinite(box.min.y)) return;
    const c = box.getCenter(new THREE.Vector3());
    _ray.set(new THREE.Vector3(c.x, box.max.y + 0.5, c.z), DOWN);
    _ray.far = 6;
    const hits = _ray.intersectObjects(surfaceTargets(excludeKey), false);
    if (!hits.length) return;
    group.position.z += hits[0].point.y - box.min.y;   // worldRoot: +local z == +world y
  }

  renderer.domElement.addEventListener('pointerdown', function (e) {
    if (e.button !== 0) return;
    clickX = e.clientX; clickY = e.clientY; clickArmed = true;
    if (playing) return;
    const p = pickDraggable(e);
    if (!p) return;
    if (liveOn && p.marker) return;    // the place marker has no meaning live
    dragTarget = p; dragging = true;
    controls.enabled = false;
    renderer.domElement.setPointerCapture(e.pointerId);
    renderer.domElement.style.cursor = 'grabbing';
    dragStartNdc.copy(dragNdc);
    p.group.getWorldPosition(dragStartWorld);
    // horizontal drag plane through the grabbed thing (world y-up)
    _dragPlane.setFromNormalAndCoplanarPoint(new THREE.Vector3(0, 1, 0), dragStartWorld);
    e.preventDefault();
  });
  renderer.domElement.addEventListener('pointermove', function (e) {
    if (!dragging) {
      if (!playing && e.buttons === 0)
        renderer.domElement.style.cursor = pickDraggable(e) ? 'grab' : '';
      return;
    }
    // object drag: the object follows the cursor onto whatever surface it points
    // at (no relative screen mapping, so no artificial reach limit)
    if (dragTarget.name) {
      const key = dragTarget.name, g = objectMeshes[key];
      const hit = surfacePointAt(e);             // world point on the drag plane
      if (hit) {
        worldRoot.worldToLocal(hit);             // map frame (z-up)
        g.position.x = hit.x; g.position.y = hit.y;
        snapToSurface(g, key);                   // exact rest height for this object
        if (liveOn) {
          liveDraggedKey = key;
          postLiveMove(key, g.position.x, g.position.y, g.position.z, false);
        } else {
          const s0 = spawn0[key];
          if (s0 && pickDeltas[key]) {
            pickDeltas[key].x = g.position.x - s0[0];
            pickDeltas[key].y = g.position.y - s0[1];
            pickDeltas[key].zAbs = g.position.z; // held until the recorded pick
          }
          if (traj) applyFrame(playhead);
        }
      }
      needsRender = true;
      return;
    }
    // %% marker drag: camera-basis mapping, clamped to the table bounds
    pointerNdc(e);
    const dist = camera.position.distanceTo(dragStartWorld);
    const halfH = Math.tan((camera.fov * Math.PI) / 360) * dist;
    const halfW = halfH * camera.aspect;
    camera.getWorldDirection(camF);
    const pitch = Math.max(0.3, Math.abs(camF.y));
    camR.set(1, 0, 0).applyQuaternion(camera.quaternion); camR.y = 0; camR.normalize();
    camU.set(0, 1, 0).applyQuaternion(camera.quaternion);
    camF.y = 0; camU.y = 0; camF.add(camU).normalize();
    _w.copy(dragStartWorld)
      .addScaledVector(camR, (dragNdc.x - dragStartNdc.x) * halfW)
      .addScaledVector(camF, (dragNdc.y - dragStartNdc.y) * (halfH / pitch));
    worldRoot.worldToLocal(_w);
    const lim = MARKER_LIMIT || objLimit();
    marker.position.x = Math.min(lim.maxX, Math.max(lim.minX, _w.x));
    marker.position.y = Math.min(lim.maxY, Math.max(lim.minY, _w.y));
    placeDelta.x = marker.position.x - PLACE0.x; placeDelta.y = marker.position.y - PLACE0.y;
    needsRender = true;
  });
  function endDrag() {
    if (!dragging) return;
    if (liveOn && dragTarget && dragTarget.name) {
      const g = objectMeshes[dragTarget.name];
      postLiveMove(dragTarget.name, g.position.x, g.position.y, g.position.z, true);
    }
    liveDraggedKey = null;
    dragging = false; dragTarget = null;
    controls.enabled = true;
    renderer.domElement.style.cursor = '';
    needsRender = true;
  }
  renderer.domElement.addEventListener('pointerup', function (e) {
    endDrag();
    if (!clickArmed) return;
    clickArmed = false;
    if (Math.hypot(e.clientX - clickX, e.clientY - clickY) > 5) return;
    const id = classifyClick(e);
    if (id && partClickCb) partClickCb(id);
  });
  renderer.domElement.addEventListener('pointercancel', function () { clickArmed = false; endDrag(); });

  function classifyClick(e) {
    pointerNdc(e);
    dragRay.setFromCamera(dragNdc, camera);
    let hits = dragRay.intersectObjects(draggableMeshes(), false);
    if (hits.length) {
      const o = hits[0].object;
      if (o.userData.simMarker) return 'place_area';
      return objectIdByKey[o.userData.simObj] || null;
    }
    if (robotModel) {
      hits = dragRay.intersectObject(robotModel.obj, true);
      for (let i = 0; i < hits.length; i++) {
        let o = hits[i].object;
        while (o && o !== scene3) {
          if (o.isURDFLink && o.name) {
            return linkToPart[String(o.name)] || (SCENE.robot && SCENE.robot.name) || null;
          }
          o = o.parent;
        }
      }
    }
    return null;
  }

  // glow entities in 3D — accepts object ids, mesh keys or segment step names
  function highlightObjects(ids) {
    const set = {};
    (ids || []).forEach(function (id) {
      id = String(id);
      set[id] = 1;
      if (SCENE && SCENE.segments) {
        const seg = SCENE.segments.find(function (s) { return s.step === id; });
        if (seg && seg.picks) set[seg.picks] = 1;
      }
    });
    for (const key in objectMeshes) {
      const on = !!set[key] || !!set[objectIdByKey[key]];
      objectMeshes[key].traverse(function (c) {
        if (c.isMesh && c.material && c.material.emissive) {
          c.material.emissive.setHex(on ? 0x39d5c8 : 0x000000);
          c.material.emissiveIntensity = on ? 0.55 : 0;
        }
      });
    }
    // direct link references: knowledge-base joint entities (l_shoulder_pan_joint → its
    // child link) and URDF-tree nodes ('urdf:<link>') resolve to link names
    const linkSet = {};
    (ids || []).forEach(function (id) {
      id = String(id);
      if (id.indexOf('urdf:') === 0) linkSet[id.slice(5)] = 1;
      const j = robotModel && robotModel.obj.joints && robotModel.obj.joints[id];
      if (j) {
        for (let i = 0; i < j.children.length; i++) {
          if (j.children[i].isURDFLink) { linkSet[j.children[i].name] = 1; break; }
        }
      }
    });
    // robot: glow meshes by part (scene.robot.parts, e.g. PR2LeftArm), by link,
    // or the whole robot when its own id is selected
    if (robotModel) {
      const robotName = SCENE && SCENE.robot && SCENE.robot.name;
      const wholeRobot = !!(robotName && set[robotName]);
      robotModel.obj.traverse(function (c) {
        if (!c.isMesh) return;
        const link = linkNameOf(c);
        const part = linkToPart[link];
        const on = wholeRobot || !!(part && set[part]) || !!linkSet[link];
        const mats = Array.isArray(c.material) ? c.material : [c.material];
        mats.forEach(function (m) {
          if (m && m.emissive) {
            m.emissive.setHex(on ? 0x39d5c8 : 0x000000);
            m.emissiveIntensity = on ? 0.45 : 0;
          }
        });
      });
    }
    // the place area: brighten the blue corner marker
    if (PLACE0) {
      const on = !!set['place_area'];
      marker.traverse(function (c) {
        if (!c.isMesh) return;
        c.material.color.setHex(on ? 0x8fdcff : 0x35a7ff);
        if (c.material.transparent) c.material.opacity = on ? 0.26 : 0.08;
      });
    }
    needsRender = true;
  }

  // %% live mode: attach to a running demo (cramera-live bridge, RViz-style)
  // The bridge streams the executing world's joints/base/objects in the exact
  // trajectory frame format; while attached, the viewer renders those instead
  // of the recording. The button appears whenever a bridge responds.
  const liveBtn = $('live-btn');
  const liveDot = $('live-indicator');   // red badge over the view
  let liveOn = false, liveTimer = null, liveFails = 0, lastSeq = -1;
  const liveCbs = [];                  // notified on attach/detach (graph tabs)
  let liveDraggedKey = null;           // object being dragged (poll must not fight it)
  let lastMovePost = 0;

  // viewer -> world: throttled while dragging, final=true on release
  function postLiveMove(key, x, y, z, final) {
    const now = performance.now();
    if (!final && now - lastMovePost < 100) return;
    lastMovePost = now;
    fetch(liveUrl() + '/move', {
      method: 'POST',
      body: JSON.stringify({ object: key, position: [round3(x), round3(y), round3(z)], final: !!final }),
    }).catch(function () {});
  }
  function round3(v) { return Math.round(v * 1000) / 1000; }

  function liveUrl() {
    const m = /[?&]live=([\w.:-]+)/.exec(window.location.search);
    return 'http://' + (m ? m[1] : (window.location.hostname + ':8765'));
  }
  function probeLive() {
    fetch(liveUrl() + '/info').then(function (r) { return r.json(); })
      .then(function (info) {
        if (liveBtn && !liveOn) liveBtn.style.display = info ? '' : 'none';
      })
      .catch(function () { if (liveBtn && !liveOn) liveBtn.style.display = 'none'; });
  }
  function applyLive(st) {
    if (!st || !st.frames) return;
    for (const k in st.frames) {
      const cut = k.indexOf('/');
      const m = modelByPrefix(cut < 0 ? '' : k.slice(0, cut));
      if (!m) continue;
      const j = m.obj.joints[cut < 0 ? k : k.slice(cut + 1)];
      if (j) j.setJointValue(st.frames[k]);
    }
    if (robotModel && st.base) setPose(robotModel.obj, st.base, st.base, 0);
    let unknown = false;
    liveStateKeys = st.objects || {};
    for (const key in liveStateKeys) {
      if (key === liveDraggedKey) continue;    // the mouse owns this one right now
      const g = objectMeshes[key];
      if (g) {
        // the running world HAS this object, so it belongs on screen, even if an
        // earlier catalog answer hid it.
        if (!g.visible) { g.visible = true; needsRender = true; }
        setPose(g, liveStateKeys[key], liveStateKeys[key], 0);
      } else unknown = true;                   // an object the demo spawned mid-run
    }
    if (unknown) syncLiveObjects();            // fetch the catalog & spawn the newcomers
    if (follow && robotCenter(_target)) controls.target.lerp(_target, 0.08);
    needsRender = true;
  }
  let livePolls = 0;
  function livePoll() {
    if (++livePolls % 45 === 0) syncLiveObjects();   // ~3 s catalog reconcile
    fetch(liveUrl() + '/state').then(function (r) { return r.json(); })
      .then(function (st) {
        liveFails = 0;
        if (st.sequenceNumber !== lastSeq) { lastSeq = st.sequenceNumber; applyLive(st); }
      })
      .catch(function () { if (++liveFails > 30) setLive(false); });
  }
  // sync the scene's objects to the ones that actually exist in the running
  // world: spawn any the viewer is missing (geometry served by the bridge),
  // hide bundle objects the demo doesn't have. Runs once per attach.
  let liveSyncing = false;
  let liveStateKeys = {};        // objects present in the newest /state payload
  function syncLiveObjects() {
    if (!liveOn || liveSyncing) return;
    liveSyncing = true;
    fetch(liveUrl() + '/objects').then(function (r) { return r.json(); })
      .then(function (d) {
        const live = d.objects || [];
        const liveKeys = {};
        live.forEach(function (o) {
          liveKeys[o.key] = 1;
          if (objectMeshes[o.key]) {                  // already present — reuse
            objectMeshes[o.key].visible = true;
            return;
          }
          const spec = { id: o.id, key: o.key, color: o.color };
          if (o.kind === 'mesh' && o.mesh) { spec.meshUrl = liveUrl() + o.mesh; spec.format = o.format; }
          else spec.box = o.size || [0.06, 0.06, 0.1];
          liveSpawned[o.key] = true;
          addObject(spec);
        });
        // Hide (don't delete) bundle objects the live world doesn't have — but
        // only once the bridge actually reports objects. An empty catalog means
        // "the demo hasn't spawned them yet" (or the world was mid-modification
        // when the bridge last bound), not "this world has no objects"; hiding
        // on that answer blanks the scene for the rest of the session.
        if (live.length || Object.keys(liveStateKeys).length) {
          for (const key in objectMeshes) {
            if (!liveKeys[key] && !(key in liveStateKeys)) objectMeshes[key].visible = false;
          }
        }
        needsRender = true;
      }).catch(function () {})
      .then(function () { liveSyncing = false; });
  }

  function setLive(on) {
    liveOn = on;
    liveCbs.forEach(function (cb) { try { cb(on); } catch (e) {} });
    if (liveDot) liveDot.classList.toggle('on', on);
    if (liveBtn) {
      liveBtn.classList.toggle('on', on);
      liveBtn.textContent = on ? '◉ LIVE — attached' : '◉ Live';
    }
    if (on) {
      playing = false;
      lastSeq = -1;
      liveStateKeys = {};
      livePolls = 0;
      syncLiveObjects();
      liveTimer = setInterval(livePoll, 66);          // ~15 Hz render updates
    } else if (liveTimer) {
      clearInterval(liveTimer);
      liveTimer = null;
      // remove objects that only existed for the live world, restore the rest
      for (const key in liveSpawned) removeObject(key);
      for (const key in objectMeshes) objectMeshes[key].visible = true;
      if (traj) applyFrame(playhead);                 // back to the recording
    }
    needsRender = true;
  }
  if (liveBtn) liveBtn.addEventListener('click', function () { setLive(!liveOn); });
  const probeTimer = setInterval(probeLive, LIVE_PROBE_INTERVAL_MS);
  probeLive();

  // %% SSAO
  let composer = null, ssaoPass = null;
  (function setupSSAO() {
    if (!(THREE.EffectComposer && THREE.RenderPass && THREE.SSAOPass && THREE.ShaderPass && THREE.CopyShader)) return;
    try {
      const w = container.clientWidth || 800, h = container.clientHeight || 600;
      composer = new THREE.EffectComposer(renderer);
      composer.addPass(new THREE.RenderPass(scene3, camera));
      ssaoPass = new THREE.SSAOPass(scene3, camera, w, h);
      ssaoPass.kernelRadius = 0.12;
      ssaoPass.minDistance = 0.001;
      ssaoPass.maxDistance = 0.04;
      composer.addPass(ssaoPass);
      const copy = new THREE.ShaderPass(THREE.CopyShader);
      copy.renderToScreen = true;
      composer.addPass(copy);
    } catch (e) { composer = null; }
  })();
  function renderFrame() {
    if (composer) composer.render();
    else renderer.render(scene3, camera);
  }

  // %% render loop
  const clock = new THREE.Clock();
  let running = true;
  function tick() {
    if (!running) return;
    requestAnimationFrame(tick);
    // imported models finish loading asynchronously, so their materials are re-tamed
    // for a while after mount; once that window closes the loop goes on-demand again
    if (models.length && clock.getElapsedTime() < MATERIAL_SETTLE_SECONDS) {
      upgradeMaterials();
      needsRender = true;
    }
    const moved = controls.update();
    if (playing && traj && !liveOn) {
      playhead += ((traj.framesPerSecond || 30) / 60) * 1.6;
      if (playhead >= traj.frames.length - 1) { playhead = traj.frames.length - 1; playing = false; stepCb('__done__'); }
      applyFrame(playhead);
      if (follow && robotCenter(_target)) controls.target.lerp(_target, 0.06);
      needsRender = true;
    }
    if (!needsRender && !moved && !controls.autoRotate) return;
    renderFrame();
    needsRender = false;
  }
  tick();

  function resize() {
    const w = container.clientWidth, h = container.clientHeight;
    if (!w || !h) return;
    renderer.setSize(w, h, false);
    if (composer) composer.setSize(w, h);
    if (ssaoPass) ssaoPass.setSize(w, h);
    camera.aspect = w / h; camera.updateProjectionMatrix();
    needsRender = true;
  }
  window.addEventListener('resize', resize);
  const containerObserver = new ResizeObserver(resize);
  containerObserver.observe(container);
  resize();

  window.RobotView = {
    onReady: function (cb) { if (finalized && traj) cb(); else readyCbs.push(cb); },
    hasTrajectory: function () { return !!traj; },
    playTrajectory: playTrajectory,
    stopTrajectory: stopTrajectory,
    isPlayingTrajectory: function () { return playing; },
    onStepStart: function (cb) { stepCb = cb; },
    setAutoRotate: function (on) { controls.autoRotate = on; controls.autoRotateSpeed = 0.5; needsRender = true; },
    setFloorVisible: function (on) { ground.visible = on; needsRender = true; },
    setFollow: function (on) { follow = on; },
    setPropsVisible: function (on) {
      for (const n in objectMeshes) objectMeshes[n].visible = on;
      marker.visible = on && !!PLACE0;
      needsRender = true;
    },
    highlightObjects: highlightObjects,
    onPartClick: function (cb) { partClickCb = cb; },
    getScene: function () { return SCENE; },
    // live bridge, shared with the graph panel (plan / statechart tabs)
    isLive: function () { return liveOn; },
    liveUrl: liveUrl,
    onLiveChange: function (cb) { liveCbs.push(cb); },
    setLabelsAlways: function (on) {
      labelsOn = !!on;
      for (const k in objectLabels) objectLabels[k].visible = labelsOn;
      needsRender = true;
    },
  };

  // %% panel wiring
  // Everything below couples the viewer to the page: buttons, overlays and the
  // event bus. The 3D code above knows nothing about other panels.
  const RobotView = window.RobotView;

  // %% bus: outbound
  RobotView.onPartClick(function (id) { bus.emit('scene:part-clicked', { id: id }); });
  RobotView.onLiveChange(function (on) { bus.emit('live:changed', { on: on, url: liveUrl() }); });

  // %% bus: inbound
  bus.on('entity:highlight', function (p) { highlightObjects((p && p.ids) || []); });

  // %% play button
  const playBtn = $('play-btn');
  playBtn.addEventListener('click', function () {
    if (!RobotView.hasTrajectory()) return;
    if (RobotView.isPlayingTrajectory()) {
      RobotView.stopTrajectory();
      playBtn.classList.remove('playing'); playBtn.textContent = '▶ Play robot motion';
    } else {
      RobotView.playTrajectory();
      playBtn.classList.add('playing'); playBtn.textContent = '⏸ Stop';
    }
  });
  RobotView.onStepStart(function (step) {
    if (step === '__done__') {
      playBtn.classList.remove('playing'); playBtn.textContent = '▶ Play robot motion';
      highlightObjects([]);
    }
    bus.emit('scene:step', { step: step });
  });

  // %% layers panel
  function bindLayer(id, method) {
    const el = $(id);
    el.addEventListener('change', function () { RobotView[method](el.checked); });
  }
  bindLayer('lyr-objects', 'setPropsVisible');
  bindLayer('lyr-labels', 'setLabelsAlways');
  bindLayer('lyr-floor', 'setFloorVisible');
  RobotView.onReady(function () {
    const legend = $('lp-legend');
    const scene = RobotView.getScene();
    if (!legend || !scene || !scene.objects) return;
    legend.innerHTML = scene.objects.map(function (entry) {
      return '<div class="li"><span class="dot" style="background:' + entry.color + '"></span>' +
        entry.id.replace(/_/g, ' ').replace(/[&<>]/g, '') + '</div>';
    }).join('');
  });

  return {
    destroy: function () {
      running = false;                       // stops the requestAnimationFrame loop
      clearInterval(probeTimer);
      if (liveTimer) { clearInterval(liveTimer); liveTimer = null; }
      containerObserver.disconnect();
      window.removeEventListener('resize', resize);
      renderer.dispose();
    },
  };
});
